### ISSUE TITLE
psh support

### ISSUE THREAD

**Issue by alpham8** [shyim/shopware-docker#45]
Hi,

we would love to see psh.phar support in this project! 💜 

For me, it worked in order not to loose the database credentials by creating a ``.psh.yaml.override`` file like this:
```
const:
  APP_ENV: "dev"
  DB_HOST: 127.0.0.1
  DB_PORT: "3306"
  DB_NAME: "sw6_dev_db"
  DB_USER: "root"
  DB_PASSWORD: "secret"
  SHOPWARE_HTTP_CACHE_ENABLED: 0
```
So, in order to get it into ``swdc build`` you could just copy the contents that you write in ``.env`` into this file above, that should do the trick 😄 

Thanks in advice 😄
