### ISSUE TITLE
Invalid image in the compose file

### ISSUE THREAD

**Issue by wahidnory** [shyim/shopware-docker#49]
Hello I'm currently trying to set this environment up on my laptop, but I'm facing an issue with the **swdc up** command.

What happens is when I do that I get the following error message:
```
... functions.sh: line 60: .... _IMAGE: invalid variable name
ERROR: The Compose file '/tmp/swdc-docker-compose.yml' is invalid because:
services.app_.image contains an invalid type, it should be a string
```

When I open the /tmp/swdc-docker-compose.yml file in the _app section the image is empty.
like so:
```
...
proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/wahid/.config/swdc/ssl:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
  app_:
    image:
    env_file:
...
```

I'm working on Linux (Manjaro) with this docker version: Docker version 19.03.8-ce, build afacb8b7f0. With zsh shell.

Did I do something wrong during setup or can you maybe point me in the direction to solve this?
