### ISSUE TITLE
Different MySQL image for specific projects

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#77]
Is it possible to have mysql:8 for sw6 project and mysql:5.7 for sw5 in the same .env file? Similar to VHOST but for mysql.

**Comment by shyim** [comment]
I guess the best would be to have custom services and volumes :thinking:

**Comment by shyim** [comment]
I have adjust it to allow extending existing docker-compose

For MySQL 8

Create `$HOME/.config/swdc/services.yml` with content

````yaml
version: '3.9'
services:
  mysql8:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql8-data:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
volumes:
  mysql8-data:
```
